language: java
jdk: 
  - openjdk8
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: webservice-deploy 
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: hjahndev/blog 

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hjahn.dev@gmail.com 